---
- name: Check CPU and Memory Usage
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather CPU and Memory Information
      shell: |
        echo "CPU Usage:"
        top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
        echo "Memory Usage:"
        free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2}'
      register: cpu_memory_info

    - name: Display CPU and Memory Information
      debug:
        msg: "{{ cpu_memory_info.stdout_lines }}"
