---
- name: Remove only files in a directory
  hosts: all
  become: yes
  tasks:
    - name: Find files in the directory
      find:
        paths: /logdir
        file_type: file
      register: files_to_remove
 
    - name: Remove files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_remove.files }}"
