- hosts: localhost
  become: true
  
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python

  tasks:
   - name: Install NGINX
     dnf:
       name: nginx
       state: present
   - name: Start Nginx service
     service:
       name: nginx
       state: started
       enabled: yes
