- hosts: localhost
  become: true
  tasks:
   - name: Install NGINX
     package:
       name: nginx
       state: present
   - name: Start HTTPD service
     service:
       name: nginx
       state: started
       enabled: yes
