---
- name: Disk Cleanup
  hosts: all
  become: yes
  tasks:
    - name: Remove logdir files
      file:
        path: /logdir/
        state: absent
        recurse: yes

    - name: Clear yum cache (RHEL/CentOS)
      command: yum clean all
      when: ansible_os_family == "RedHat"
