---
- name: Gather machine configuration
  hosts: localhost
  tasks:
    - name: Gather system information
      ansible.builtin.setup:
        gather_subset:
          - 'hardware'
          - 'network'
          - 'virtual'
          - 'facter'
          - 'ohai'
    - name: Display gathered information
      ansible.builtin.debug:
        var: ansible_facts
