---
- name: Update VCPU quota in Azure
  hosts: all
  gather_facts: false
  tasks:
    - name: Update VCPU quota
      azure_rm_quota:
        resource_group: dfs-webb-rg
        name: ansible-demo
        location: Central US (Zone 1)
        quota:
          vcpu: 3
      register: quota_result

    - name: Display quota result
      debug:
        var: quota_result
