---
- name: Resize Azure VM
  hosts: all
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: /usr/bin/python3
    resource_group: "dfs-webb-rg"
    vm_name: "ansible-demo"
    new_vm_size: "Standard_D2s_v5"  # Change to desired size

  tasks:
    - name: Stop the VM before resizing
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        started: no
      environment:
        AZURE_SUBSCRIPTION_ID: "64c8eb52-f677-4a21-b89a-820a5f9bd5a8"
        AZURE_CLIENT_ID: "cc330866-d3bf-48a0-ae84-4079d48eb534"
        AZURE_SECRET: "WHU8Q~YliUYmnVhd6CRr3ABFZyf8_ULJf8CCja-N"
        AZURE_TENANT: "189de737-c93a-4f5a-8b68-6f4ca9941912"
  

    - name: Resize the VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ new_vm_size }}"
        started: no
      environment:
        AZURE_SUBSCRIPTION_ID: "64c8eb52-f677-4a21-b89a-820a5f9bd5a8"
        AZURE_CLIENT_ID: "cc330866-d3bf-48a0-ae84-4079d48eb534"
        AZURE_SECRET: "WHU8Q~YliUYmnVhd6CRr3ABFZyf8_ULJf8CCja-N"
        AZURE_TENANT: "189de737-c93a-4f5a-8b68-6f4ca9941912"   

    - name: Start the VM after resizing
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        started: yes
